# Generated by Django 2.2.7 on 2019-11-12 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('travelIncluded', models.CharField(max_length=200)),
                ('hotelName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.Hotel')),
            ],
        ),
    ]
