# Generated by Django 2.2.7 on 2019-11-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
