# Generated by Django 2.2.7 on 2019-11-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='location',
            new_name='country',
        ),
    ]
