# Generated by Django 2.2.7 on 2019-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20191114_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='packageImage',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
