# Generated by Django 2.2.7 on 2019-11-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_auto_20191114_1946'),
        ('packages', '0004_package_packageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='country',
        ),
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='attractions.Attraction'),
        ),
    ]
