# Generated by Django 2.2.7 on 2019-11-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20191119_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.AddField(
            model_name='package',
            name='country',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
