# Generated by Django 2.2.7 on 2019-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20191119_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
