# Generated by Django 2.2.7 on 2019-11-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_auto_20191119_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='packageImage',
        ),
    ]
