# Generated by Django 2.2.7 on 2019-11-30 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_remove_package_packageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='endDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='package',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
