# Generated by Django 2.2.7 on 2019-11-30 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_auto_20191130_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='endDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='startDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
