# Generated by Django 2.2.7 on 2019-11-30 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_auto_20191130_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='startDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
