# Generated by Django 2.2.7 on 2019-11-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='street',
        ),
    ]
