# Generated by Django 2.2.7 on 2019-11-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0003_auto_20191114_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractionName', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='packages.Package')),
            ],
        ),
    ]
