# Generated by Django 2.2.7 on 2019-11-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
