# Generated by Django 2.2.7 on 2019-11-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20191114_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
