# Generated by Django 2.2.7 on 2019-11-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_attraction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
