# Generated by Django 2.2.7 on 2019-11-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_auto_20191114_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='image2',
        ),
    ]
