# Generated by Django 2.2.7 on 2019-11-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_remove_attraction_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image1',
            field=models.ImageField(blank=True, upload_to='attractions/photos/%Y/%m/%d/'),
        ),
    ]
